version: '3.8'

services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=consult_db
      - POSTGRES_USER=consult_user
      - POSTGRES_PASSWORD=consult_password
    ports:
      - "5432:5432"
    network_mode: host

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    network_mode: host

  backend:
    build: ./backend
    command: uvicorn config.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - DEBUG=0
      - SECRET_KEY=change_me_in_prod
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend,34.93.19.177
      - DATABASE=postgres
      - DB_NAME=consult_db
      - DB_USER=consult_user
      - DB_PASSWORD=consult_password
      - DB_HOST=localhost
      - DB_PORT=5432
      - REDIS_URL=redis://localhost:6379/0
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - CORS_ALLOWED_ORIGINS=http://34.93.19.177,http://localhost:3000,http://localhost
      - CSRF_TRUSTED_ORIGINS=http://34.93.19.177,http://localhost:3000,http://localhost
    depends_on:
      - db
      - redis
    network_mode: host

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://34.93.19.177/api/v1
        - VITE_WS_URL=ws://34.93.19.177/ws
    ports:
      - "3000:80"
    depends_on:
      - backend

  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - backend
      - frontend
    network_mode: host

volumes:
  postgres_data:
  static_volume:
  media_volume:


networks:
  consult_network:
    driver: bridge
